jobs:
  build:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      # - go/load-cache
      # - go/mod-download
      # - go/save-cache
      - run:
          name: 'trying to build the backend'
          command: |
            go build main.go
            ls -la 
            pwd
            ./main 
orbs:
  go: circleci/go@1.7.1
version: 2.1
workflows:
  main:
    jobs:
      - build
