version: 2.1

jobs:
  build-backend:
    docker:
      - image: cimg/go:1.17.5
    steps:
      - checkout
      - run:
          name: 'run go build'
          command: go run build main.go

workflows:
  default:
    jobs:
      - build-backend
